using System;
using System.IO;
using System.Text;

namespace Diacom.TraceListener
{
	/// <summary>
	/// Implements access to HTML formatted header and footer for log file.
	/// </summary>
	internal class HTML
	{
		private string Title = String.Empty;
		private string NewLine = Environment.NewLine;

		/// <summary>
		/// Creates new instance for HTML formatted log header and footer.
		/// </summary>
		/// <param name="aTitle">The title of the document.</param>
		public HTML(string aTitle)
		{
			this.Title = aTitle;
		}
			
		/// <summary>
		/// Gets the header for HTML formatted document based on the title set by constructor.
		/// </summary>
		public string Header
		{
			get
			{
				StringBuilder TheHeader = new StringBuilder();
				TheHeader.Append("<html>");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("<head>");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("<!-- Generated by TraceOutputListener::HTML -->");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=unicode\">");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("<title>");
				TheHeader.Append(this.Title);
				TheHeader.Append("</title>");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("</head>");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("<body bgcolor=\"#000000\">");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("<font color=\"#808080\">");
				TheHeader.Append(this.Title);
				TheHeader.Append("</font><hr>");
				TheHeader.Append(this.NewLine);
				TheHeader.Append("<pre><font color=\"#00ff00\">");
				TheHeader.Append(this.NewLine);
				return TheHeader.ToString();
			}
		}

		/// <summary>
		/// Gets the footer for HTML formatted document.
		/// </summary>
		public string Footer
		{
			get
			{
				StringBuilder TheFooter = new StringBuilder();
				TheFooter.Append(this.NewLine);
				TheFooter.Append("</font></pre><hr>");
				TheFooter.Append(this.NewLine);
				TheFooter.Append("<font color=\"#808080\">Created ");
				TheFooter.Append(DateTime.Now.ToString("yyyy.MM.dd, HH:mm:ss:fff"));
				TheFooter.Append(" by APCService::TraceOutputListener.<br>");
				TheFooter.Append(this.NewLine);
				TheFooter.Append("OOO \"Diacom\"&reg;, 127434, Moscow, Russia, Dmitrovskoe Shosse, 2. Tel: +7(095) 777-9698, voip.dia.com.ru, <a href=\"http://www.dia.com.ru\">www.dia.com.ru</a></font>");
				TheFooter.Append(this.NewLine);
				TheFooter.Append("</body>");
				TheFooter.Append(this.NewLine);
				TheFooter.Append("</html>");
				TheFooter.Append(this.NewLine);
				return TheFooter.ToString();
			}
		}
	}
}
